version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=mohaned
     - MYSQL_DATABASE=achatdb
     - MYSQL_USER=mohaned
     - MYSQL_PASSWORD=mohaned
    volumes:
     - /home/mysql/data:/var/lib/mysql


