version: "3"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=tpachato
    ports:
      - 3306:3306
    volumes:
      - tpachato:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./spring-app
    restart: on-failure
    env_file: ./.env
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpachato?createDatabaseIfNotExist=true&useSSL=false",
        "spring.datasource.username" : root,
        "spring.datasource.password" : 
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:

